travis:
  secure:
    BINSTAR_TOKEN: NRxUNHQg4PsKUWhmfwfFOnZzMQYWkPENvmszZG657YhVdEEL/YzPRjOZAKF4vBbZ8CcE5OiOiLxQDOPumkvDpBor4nxk3WcZ9t7pH+4qtM+vFbTx2Zivw/sE/8AkM3zTeyXu1PZ6F2QaQ/jbgrEtRZ5nFr7rL8a3Lin4di5wVl+7d6GMJ9wIkxm6Y0pZWQ/PAptN6oU20k2nLaauQQJyfaU1BZ0uWzjvPI3yNFjoL0N1tuqXmoI6JNNkE+N8GS34PRDYnm2ZQlpeDW8DS9Du/6zFpoX9Km4mhC5Wrlj7zn+aMr7jJ4tfHupzQ/A8/1eQeUdkqFR/mymhKDVxpKXOo14BW6hv64B7XXiYQnfu/RNPcQLuXLuxUISaNPZkocJ0G6vSdbGJzcLEL7meMWxUuPZ6dzcd+QrxHhVM3uXpRVj1Zu/ZS7F7qBzY5/EjOQMdwB823orlB8JkyfF2RVlIupfHVdXc0YbQbi5lfEvKlSxojl15V3moYWhS21Z+S0vKTJ+opEc2ZJTIZHIbD+LGs3cNNASkPji6ffnW6OdL2omPgjjm6UAkNdLvoDK4TPnkaJL//i1Na6nRs8k3zOp8/DyvZiVaG3LYcFaeH57E+PjevB7L4qNbcuZ/GVEO/XI6HRFdjx4nbODr0nPuQDla0BdOic/z7yeZbsTwNQCKIAg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
