travis:
  secure:
    BINSTAR_TOKEN: Q0OyfrmKxelRZkWffoQ2UaHhP7ZV2pITdJ7OVUrBga2OGCVMnVgBKHa9KZeLk5IDZLtnU5oh+uR2WItdpvKN2GJCrW8qo2OoXbDPh9xgFIP8431Dusmlh0v5nuczD2e3+L24wp+dUiWoJmPFvRU7Y0juLIeyAHlM0BMbQ+YwfDJnU5uwjzKlJqDBVOLThFFTKQwgEt1MZmqe+dT1YCW2I8a5azMcrljfJ+UYF4dhtVX0hP3gW/dPNKe9KfLwVthHblwNcXTtXNYWf6qhNAA9d2Lz2q0Fzdrb1i9j7CiNPdP4wF+SDFJKz13NqLCGhRmt9TqoXOpDMbuTuMdcFQhMx2Fbie7CCNGkbZgOVudIZjPYsFvsOWUP+5c8HbRUhaTe1gxrDGjuOVMkSsRyamgNqaw8MYlMd19XfUN9aFA3miE7BAUbel4+kjHUmr6fmiMvQvbpphhf0pc9xgEeuesXJP5Amp8Dnf1Rl+hMTN3g50IUO7FeGq3emQ2F/jfGdKVeoeDFI9dIrEZXOIBRUT0D9uMVF5Wxs6S8wayIxo8DveI/vn3eF6nLB9x6xdXw8StXyxKplJZOPM87YLqI5KOqdlr4tCiQAQFzZwRonWG7A49MzJVYfiq7rXf6Ymnumx+ceIkn4cnoTDiToNf+WYjDhkHcwIm4i1D7l2eB5FBu6UY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
